---
- name: "Donwloading and Installing Keys to Download Mongodb"
  # We are going to install the version 7.0
  shell: |
    wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | tee /etc/apt/trusted.gpg.d/server-7.0.asc
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
  become: true
  become_method: sudo

- name: "Installing Mongodb"
  apt:
    pkg:
      - mongodb-org
      - mongodb-mongosh
    state: present
    update_cache: true
  become: true
  become_method: sudo
