---
- name: "Downloading and Installing Keys to Download VS Code"
  shell: |
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
    sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
    rm -f packages.microsoft.gpg
  become: true
  become_method: sudo
- name: "Installing apt-transport-https for VS Code and Update Cache"
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: true
  become: true
  become_method: sudo

- name: "Installing VS Code"
  apt:
    name: code-insiders
    state: present
  become: true
  become_method: sudo
