---
- name: "Installing Golang"
  apt:
    name: "golang-go"
    state: present
  become: true
  become_method: sudo

# Installing Firejail from source
- name: "Cloning Firejail repository"
  git:
    repo: "https://github.com/netblue30/firejail.git"
    dest: "/tmp/firejail"

- name: "Installing firejail"
  shell: |
    cd /tmp/firejail
    sudo ./configure && make && sudo make install-strip
