---
- name: "Installing Golang"
  apt:
    name: "golang-go"
    state: present
  become: true
  become_method: sudo

- name: "Installing venv"
  apt:
    name: "python3.11-venv"
    state: present
  become: true
  become_method: sudo

- name: "Installing firejail"
  apt:
    name: "firejail"
    state: present
  become: true
  become_method: sudo
