---
- name: "Installing Golang"
  apt:
    name: "golang-go"
    state: present
  become: true
  become_method: sudo

# Installing Firejail from source
- name: "Cloning Firejail repository"
  git:
    repo: "https://github.com/netblue30/firejail.git"
    dest: "/tmp/firejail"

- name: "Installing firejail"
  shell: |
    cd /tmp/firejail
    sudo ./configure && make && sudo make install-strip

# Installing Python venv
- name: "Adding deadsnakes repository for python3.11"
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    codename: trusty
  become: true
  become_method: sudo

- name: "Installing venv"
  apt:
    name: "python3.11-venv"
    state: present
    update_cache: true
  become: true
  become_method: sudo
