---
# Directory Handling
- name: "Creating workspace directory"
  file:
    path: "{{ ansible_env.HOME }}/workspace/"
    state: directory

# Decompressing rockyou.txt file
- name: "Checking if rockyou.txt.gz exists"
  stat:
    path: /usr/share/wordlists/rockyou.txt.gz
  register: rockyou_txt_exists

- name: "Decompressing rockyou.txt.gz"
  shell: |
    cd /usr/share/wordlists
    gzip -d rockyou.txt.gz
  become: true
  become_method: sudo
  when: rockyou_txt_exists.stat.exists

# Downloading Wordlists
- name: "Checking if /usr/share/wordlists directory exists"
  stat:
    path: /usr/share/wordlists/
  register: wordlists_dir_exists

- name: "Installing SecLists repository"
  git:
    repo: "https://github.com/danielmiessler/SecLists.git"
    dest: "/usr/share/wordlists/SecLists"
  become: true
  become_method: sudo
  when: wordlists_dir_exists.stat.exists

- name: "Installing Auto_Wordlists repository"
  git:
    repo: "https://github.com/carlospolop/Auto_Wordlists.git"
    dest: /usr/share/wordlists/Auto_Wordlists
  become: true
  become_method: sudo
  when: wordlists_dir_exists.stat.exists