---
# Directory Handling
- name: "Create workspace directory"
  file:
    path: "{{ ansible_env.HOME }}/workspace/"
    state: directory

# Decompressing rockyou.txt file
- name: Check if file exists using stat module
  stat:
    path: /usr/share/wordlists/rockyou.txt.gz
  register: file_status

- name: "Decompress rockyou.txt.gz"
  shell: |
    cd /usr/share/wordlists
    gzip -d rockyou.txt.gz
  become: true
  become_method: sudo
  when: file_status.stat.exists