---
# Polybar
- name: "Cloning Polybar Repository"
  git:
    repo: "https://github.com/polybar/polybar"
    dest: "/tmp/polybar"
    recursive: true

- name: "Installing Polybar"
  shell: |
    cd /tmp/polybar
    mkdir build
    cd build
    cmake ..
    make -j$(nproc)
    make install
  become: true
  become_method: sudo

- name: "Deleting Polybar Installation Files"
  file:
    path: "/tmp/polybar"
    state: absent
  become: true
  become_method: sudo

# Picom
- name: "Cloning Picom Repository"
  git:
    repo: "https://github.com/ibhagwan/picom.git"
    dest: "/tmp/picom"

- name: "Installing Picom"
  shell: |
    cd /tmp/picom
    git submodule update --init --recursive
    meson --buildtype=release . build
    ninja -C build
    ninja -C build install
  become: true
  become_method: sudo

- name: "Deleting Picom Installation Files"
  file:
    path: "/tmp/picom"
    state: absent
  become: true
  become_method: sudo
